SELECT DISTINCT ?term
WHERE {
  { ?s1 ?p1 ?term . }
  UNION
  { ?term ?p2 ?o2 . }
  FILTER(isIRI(?term) && (regex(str(?term), UCASE("pizza_")) || regex(str(?term), "https://w3id.org/trustedai/cco/pizza")))
}
